% createMetamers.m
%
% by William F. Broderick
%
% creates the V1 and V2 metamers used to test the sco model. Note
% that these are spectrally matched noise (V1) and the outputs of
% Eero's texture model (V2).
% 
% based off of example1.m in textureSynth
% 
% this requires both Eero's textureSynth and matlabPyrTools

function createMetamers(textureSynthPath, pyrToolsPath, knkpath, imgDir, outputDir, imgIdx, numScales, numOrientations, sizeNeighborhood, Niter, seeds)
% arguments:
% 
% textureSynthPath: string, path to your textureSynth folder, which
% we'll add to the matlab path
%
% pyrToolsPath: string, path to your matlabPyrTools folder, which
% we'll add to the matlab path
% 
% imgDir: template string to the images you want are contained. Should
% be something like the following: /path/to/imgs/*.jpg, so that we
% only find the images of the right type (we will call dir(imgDir)).
% 
% outputDir: string, directory to save these metamers (and the
% original image used) in.
% 
% imgIdx: vector, specifying which images from imgDir to use.
% 
% numScales: integer, the number of scales to use in filters for
% generating metamers. recommended value 4.
% 
% numOrientations: integer, the number of orientations in the
% filters for generating metamers. recommended value 4
% 
% sizeNeighborhood: integer, spatial neighborhood for generating metamers
% (must be an odd number!). recommended value 7
% 
% for details on these three, see the textureSynth library and
% the paper: "A Parametric Texture Model based on Joint Statistics of
% Complex Wavelet Coefficients".  J Portilla and E P Simoncelli. Int'l
% Journal of Computer Vision, vol.40(1), pp. 49-71, Dec 2000.
% 
% Niter: integer, how many iterations the textureSynthesis
% algorithm should go through. recommended 10 to 50.
% 
% seeds: vector of integers, random seeds to use for generating the
% initial random images. The number of metamers we make will be
% equal to the length of this vector.

    addpath(genpath(textureSynthPath));
    addpath(genpath(pyrToolsPath));
    addpath(genpath(knkpath));
    
    if isempty(find(imgDir=='*'))
        error('imgDir must contain a wildcard in order for this to work! see docstring for example')
    end
    imgPaths = dir(imgDir);
    lastSlash = find(imgDir=='/');
    lastSlash = lastSlash(end);
    imgDir = imgDir(1:lastSlash);
    
    if ~strcmp(outputDir(end), '/')
        outputDir = [outputDir '/'];
    end
    
    for ii=imgIdx
        % our input image must be a double
        imgName = imgPaths(ii).name;
        baseImage = double(imread([imgDir, imgName]));
        % need to make sure image is grayscale
        baseImage = mean(baseImage, 3);
        % need to make sure image is square and can be divided by 2 five times
        % evenly
        cutSize = floor(min(size(baseImage))/2^6) * 2^6;
        baseImage = baseImage(1:cutSize, 1:cutSize);
        
        lastPeriod = find(imgName=='.');
        imgName = imgName(1:lastPeriod-1);
        
        imwrite(baseImage/255, [outputDir imgName '.png']);

        params = textureAnalysis(baseImage, numScales, numOrientations, sizeNeighborhood);
        
        % metamer size must be some multiple of
        % 2^(numScales+2). for now, we try to make the size of the
        % metamer image about the same as the size of the input image
        metamerSize = 2^(numScales + 2);
        metamerSize = ceil(size(baseImage, 1) / metamerSize) * metamerSize;
        
        for jj=1:length(seeds)
            % Based on the methods of Freeman, 2013
            % (http://www.nature.com/neuro/journal/v16/n7/full/nn.3402.html#methods),
            % the V1 metamer should be spectrally matched noise,
            % generated by "randomizing the phase but matching the
            % complete two-dimensional power spectra", which is what
            % this does. We only want the real component, the
            % imaginary ends up being some constant.
            V1Metamer = real(ifft2(fft2(baseImage) .* generaterandomphase(size(baseImage, 1))));
            % The V1Metamer can have some weird values. This makes
            % sure it lies between 0 and 1. Unfortunately, I can't
            % figure out what the theoretical min and max values
            % would be.
            % [mn, mx] = range2(V1Metamer);
            % V1Metamer = (V1Metamer + abs(mn)) / (abs(mn) + abs(mx));
            % center the mean and then clip
            V1Metamer = V1Metamer - mean(V1Metamer(:)) + 127.5;
            V1Metamer(V1Metamer>255) = 255;
            V1Metamer(V1Metamer<0) = 0;
            
            % with these inputs, textureSynthesis uses white noise
            % as the seed image
            V2Metamer = textureSynthesis(params, [metamerSize metamerSize seeds(jj)], Niter);
        
            V2MetamerScaled = V2Metamer * (var(V1Metamer(:)) / var(V2Metamer(:)));
            
            % imwrite requires them to lie between 0 and 1, so we scale
            % them down
            imwrite(V1Metamer/255, [outputDir 'V1Met-' imgName '-' num2str(seeds(jj)) '.png']);
            imwrite(V2Metamer/255, [outputDir 'V2Met-' imgName '-' num2str(seeds(jj)) '.png']);
            imwrite(V2MetamerScaled/255, [outputDir 'V2MetScaled-' imgName '-' num2str(seeds(jj)) '.png']);            
        end
    end
    
    close all;
    
    
end
